import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

// SPEC-001:R2, R3, R7 — runtime pinning, TypeScript strict mode, and the
// standard npm scripts.
const root = process.cwd();

function readJson(relativePath: string) {
	return JSON.parse(readFileSync(path.join(root, relativePath), 'utf8'));
}

/** tsconfig.json (as generated by SvelteKit) contains `//` line comments,
 *  which are valid JSONC but not valid JSON. Strip them before parsing. */
function readJsonc(relativePath: string) {
	const withoutComments = readText(relativePath)
		.split('\n')
		.map((line) => line.replace(/\/\/.*$/, ''))
		.join('\n');
	return JSON.parse(withoutComments);
}

function readText(relativePath: string) {
	return readFileSync(path.join(root, relativePath), 'utf8');
}

describe('Node runtime pinning (SPEC-001:R2)', () => {
	it('package.json declares engines.node as >=24 <25', () => {
		const pkg = readJson('package.json');
		expect(pkg.engines?.node).toBe('>=24 <25');
	});

	it('.nvmrc pins Node 24', () => {
		expect(readText('.nvmrc').trim()).toBe('24');
	});

	it('vite.config.ts wires up @sveltejs/adapter-node (no separate svelte.config.js in this SvelteKit version — see TASK-001)', () => {
		expect(readText('vite.config.ts')).toContain('adapter-node');
	});
});

describe('TypeScript strict mode (SPEC-001:R3)', () => {
	it('tsconfig.json enables strict mode', () => {
		const tsconfig = readJsonc('tsconfig.json');
		expect(tsconfig.compilerOptions.strict).toBe(true);
	});
});

describe('standard npm scripts (SPEC-001:R7)', () => {
	const REQUIRED_SCRIPTS = [
		'dev',
		'build',
		'preview',
		'check',
		'check:privacy',
		'lint',
		'format',
		'test',
		'test:unit',
		'test:integration',
		'test:e2e'
	];

	it.each(REQUIRED_SCRIPTS)('defines the "%s" script', (name) => {
		const pkg = readJson('package.json');
		expect(pkg.scripts, `expected package.json to have a "${name}" script`).toHaveProperty(name);
	});
});
